# Generated by Django 3.2.7 on 2021-10-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dapartament',
            new_name='department',
        ),
    ]
